[plugin]
repository = "https://github.com/KhloeLeclair/WTSync.git"
commit = "bad99025cde42e0e6ee93eb3ea0353bfc49c8bc0"
owners = [ 
	"KhloeLeclair"
]
project_path = ""
changelog = """
* Added: Ability to open the Duty Finder to a relevant duty when clicking a Wondrous Tails entry directly in the Wondrous Tails UI.

* Fixed: Bug where we would attempt to open the Duty Finder to a roulette while in an instance.
* Maintenance: Update the various API endpoints to new URLs.
"""